tools:
  - class_name: "evalhub.tools.code_tool.CodeTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for execute code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "self-contained code needs to be execute."
          required: ["code"]
